CLOUDPULSE_DEBUG: True
CLOUDPULSE_VERBOSE: True
CLOUDPULSE_DATABASE: cloudpulse
CLOUDPULSE_DATABASE_USER: cloudpulse
CLOUDPULSE_DATABASE_PASSWD: cloudpulse
CLOUDPULSE_OPENSTACK_USER: cloudpulse
CLOUDPULSE_OPENSTACK_PASSWD: cloudpulse
CLOUDPULSE_PUBLIC_PORT: 9999
CLOUDPULSE_INTERNAL_PORT: 9999
CLOUDPULSE_ADMIN_PORT: 9999
CLOUDPULSE_REPO: https://github.com/openstack/cloudpulse.git