---

- name: "Cloning cloudpulse client"
  git:
    repo: https://github.com/openstack/python-cloudpulseclient.git
    dest: "{{OPENSTACK_DIR}}/python-cloudpulseclient"

- name: "Install cloudpulse client dependencies"
  pip: requirements="{{OPENSTACK_DIR}}/python-cloudpulseclient/requirements.txt"

- name: "Install python-cloudpulse client"
  shell: "cd {{OPENSTACK_DIR}}/python-cloudpulseclient/ && python setup.py install"