---

- name: "Clone cloudpulse to {{OPENSTACK_DIR}} "
  git:
    repo: "{{CLOUDPULSE_REPO}}"
    dest: "{{OPENSTACK_DIR}}/cloudpulse"

- name: "Install cloudpulse requirements"
  pip: requirements="{{OPENSTACK_DIR}}/cloudpulse/requirements.txt"

- name: "Install cloudpulse"
  shell: "cd {{OPENSTACK_DIR}}/cloudpulse/ && python setup.py install"

- name: "Create cloudpulse server config"
  template: src=cloudpulse.conf dest="{{OPENSTACK_DIR}}/cloudpulse/etc/cloudpulse/cloudpulse.conf"
  run_once: True

- name: "Starting cloudpulse server"
  shell: "nohup cloudpulse-server --config-file {{OPENSTACK_DIR}}/cloudpulse/etc/cloudpulse/cloudpulse.conf > /tmp/cloudpulse.log 2>&1 &"
  run_once: True

